version: '2'
services:
  android-build:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: ./gradlew assembledebug
    volumes:
      - ./docker/outputs/:/project/app/build/outputs
